--INSERT INTO FILE_INFO (FILE_ID, FILE_NAME, FILE_CONTENT)
    --VALUES ("100", "test.txt", RAWTOHEX("test fileInfo"));

--INSERT INTO  FILE_METADATA (METADATA_ID, KEY, VALYE, FILE_ID)
    --VALUES ("500","size", "12", "100" );

--INSERT INTO  FILE_METADATA (METADATA_ID, KEY, VALYE, FILE_ID)
--VALUES ("501","createdy", "Deepa", "100" );